projetofunc/funcionarios/urls.py
from django.urls import path
from funcionarios import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'funcionarios'

urlpatterns = [
    #crud
    path('funcionarios/<int:funcionariouni_id>/details/', views.funcionariouni, name='funcionariouni'),
    path('funcionarios/create', views.create, name='create'),
    path('funcionarios/<int:funcionariouni_id>/update/', views.funcionariouni, name='funcionariouni'),
    path('funcionarios/<int:funcionariouni_id>/delete/', views.funcionariouni, name='funcionariouni'),

    path('pesquisa', views.pesquisa, name='pesquisa'),
    path('', views.index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()

projetofunc/projetofunc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('funcionarios.urls')),
    path('admin/', admin.site.urls),
]

projfunc/projfunc/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

projetofunc/funcionarios/models.py
from django.db import models

# Create your models here.

class Funcionario(models.Model):
    apelido = models.CharField(max_length=32)
    nome_Completo = models.CharField(max_length=100)
    data_Nasc = models.DateField()
    stacks = models.TextField(max_length=200, blank=True)

    def __str__(self) -> str:
        return f'{self.nome_Completo}'

projetofunc/funcionarios/forms.py
from django import forms
from funcionarios.models import Funcionario

class FuncForm(forms.ModelForm):
        
        nome_Completo = forms.CharField(
            widget = forms.TextInput(
                attrs={
                    'placeholder': 'Fulano da Silva Costa',
                }
            ),
            label='Nome Completo',
            max_length=100,
        )

        apelido = forms.CharField(
            widget = forms.TextInput(
                attrs={
                    'placeholder': 'Zeca',
                }
            ),
            label='Apelido',
            max_length=32,
        )

        data_Nasc = forms.DateField(
            widget = forms.DateInput(),
            label='Data de Nascimento'
        )

        stacks = forms.CharField(
            widget = forms.TextInput(
                attrs={
                    'placeholder': 'C#, Python, Django ou Vazio',
                },
            ),
            label='Stacks',
            required=False,
        )

        class Meta: 
            model = Funcionario
            fields = (
                'nome_Completo', 'apelido', 'data_Nasc', 'stacks',
            )
        
        def clean(self):
        #cleaned_data = self.cleaned_data
            return super().clean()

projetofunc/funcionarios/views/func_forms.py
from django.shortcuts import render, redirect
from pathlib import Path
import json
from funcionarios.forms import FuncForm

CAMINHO_ATUAL = Path(__file__).parent / 'dadosfuncionarios.json'

def create(request):

    if request.method == 'POST':

        form = FuncForm(request.POST)
        context = {
            'form': form,
        }

        if form.is_valid():
            form.save()
            with open(CAMINHO_ATUAL, 'a') as arquivo:
                json.dump(request.POST, arquivo, ensure_ascii=True, indent=4)
            arquivo.close()
            return redirect('funcionarios:create')
        

        return render(
            request,
            'funcionarios/create.html',
            context
        )
    
    context = {
        'form': FuncForm()
    }

    return render(
        request,
        'funcionarios/create.html',
        context
    )

projetofunc/funcionarios/views/func_views.py
from django.shortcuts import render, redirect
from funcionarios.models import Funcionario
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator



def index(request):
    funcionarios = Funcionario.objects \
    .order_by('-id')

    paginator = Paginator(funcionarios, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'MedFutura - Funcionários',
    }

    return render(
        request,
        'funcionarios/index.html',
        context
    )

def funcionariouni(request, funcionariouni_id):
    unidade_func = Funcionario.objects.filter(pk=funcionariouni_id).first()

    if unidade_func is None:
        raise Http404()

    context = {
        'funcionario': unidade_func,
    }

    return render(
        request,
        'funcionarios/funcionariouni.html',
        context
    )

def pesquisa(request):
    valor_pesquisa = request.GET.get('q', '').strip()

    if valor_pesquisa == '':
        return redirect('funcionarios:index')

    funcionarios = Funcionario.objects \
        .order_by('-id')\
        .filter(Q(nome_Completo__icontains=valor_pesquisa) |
                Q(apelido__icontains=valor_pesquisa) |
                Q(stacks__icontains=valor_pesquisa))\
    
    paginator = Paginator(funcionarios, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)


    context = {
        'page_obj': page_obj,
        'site_title': 'Pesquisa - ',
        'valor_pesquisa': valor_pesquisa,
    }

    return render(
        request,
        'funcionarios/index.html',
        context
    )

projetofunc/funcionarios/templates/funcionarios/create.html
{% extends 'global/base.html' %}

{% block content %}
  <h1>Registrar Funcionário</h1>
  <div class="form-wrapper">

    <h2>Funcionário</h2>

    <form 
      action="{% url 'funcionarios:create' %}"
      method="POST"
      enctype="multipart/form-data"
    >

    {% csrf_token %} 
      <div class="form-content">
        {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {{ field.errors }}
        </div>
        {% endfor %}
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Criar</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

projetofunc/funcionarios/templates/funcionarios/funcionariouni.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ funcionario.nome_Completo }}
        </h1>
        <p><strong>ID:</strong> {{ funcionario.id }}</p>
        <p><strong>Apelido: </strong> {{ funcionario.apelido }}</p>
        <p><strong>Data de Nascimento:</strong> {{ funcionario.data_Nasc }}</p>
        <p><strong>Stacks: </strong> {{ funcionario.stacks }}</p>
    </div>
{% endblock content %}

projetofunc/funcionarios/templates/funcionarios/index.html
{% extends 'global/base.html' %}

{% block content%}
    {% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Funcionários
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Nome</th>
                    <th class="table-header">Data de Nascimento</th>
                    <th class="table-header">Apelido</th>
                    <th class="table-header">Stacks</th>
                </tr>
                <tbody>
                    {% for funcionario in page_obj %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" href="{% url 'funcionarios:funcionariouni' funcionario.id %}">
                                {{ funcionario.id }}
                            </a>
                        </td>
                        <td class="table-cel">
                            {{ funcionario.nome_Completo}}
                        </td>
                        <td class="table-cel">
                            {{ funcionario.data_Nasc }}
                        </td>
                        <td class="table-cel">
                            {{ funcionario.apelido }}
                        </td>
                        <td class="table-cel">
                            {{ funcionario.stacks }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </thead>
        </table>
    </div>
    {% else %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum funcionário encontrado.
        </h1>
    </div>
    {% endif%}
{% endblock content%}